### ISSUE TITLE
why it's showing me wrong?

### ISSUE THREAD

**Issue by Ovix91** [geekcomputers/Python#1456]
according to video saw it mustn't show 10 and 30,i did it once and it works but now it doesn't, what should i do?
i think i must know how does it work in behind the scenes

prices = [10,20,30]
total = 0
for price in prices:
    total += price
    print(f'total: {total}')

it showed me 10 30 60
it mustn't show me 10 and 30

**Comment by BeASTBLASTER** [comment]
prices = [10,20,30]
total = 0
for price in prices:
    total += price   #Your Problem is in simple index problem
print(f'total: {total}')
Now when you run it doesn't  show the error because due to indexing problem now you see first your total price is 0 at start
when price element comes 10 it get added to total which is 0 then it get 10. after price value change to 20 and total value is 10 we get new total value as 30 then 60

**Comment by Ovix91** [comment]
what do you mean indexing problem?

**Comment by BeASTBLASTER** [comment]
your print command was inside the for loop which leads to answer 10 and 30
I have given space but it is not showing I will add the program in above so that you can understand

**Comment by BeASTBLASTER** [comment]
Do you understand the answer .

**Comment by Ovix91** [comment]
> Do you understand the answer .

Yes yes,thank you:)
