### ISSUE TITLE
Error in the following program

### ISSUE THREAD

**Issue by Prince326** [geekcomputers/Python#719]
https://github.com/geekcomputers/Python/blob/master/Weather%20Scrapper/weather.py

when i run the above program it gives the following error-

28 Time = datetime.now().strftime("%H:%M")
---> 29 Date = out2.find('span', attrs={'class': 'date'}).get_text()
     30 Temperature = out2.find('span', attrs={'class': 'temp'}).get_text()
     31 Temperature = " ".join(Temperature.split())

AttributeError: 'NoneType' object has no attribute 'find'

**Comment by itsvinayak** [comment]
This [program](https://github.com/geekcomputers/Python/blob/master/Weather%20Scrapper/weather.py) use beautifulsoup to scrap webpage to find the weather info. the error you are getting is because it is unable to find `"small-12 medium-4 large-3 columns forecast-wrap"` class in requested webpage so `soup = BeautifulSoup(html, 'lxml')`  function  returns `None` .Edit code a bit and add **if statement** or **try and expect block** and you are good to go.

**Comment by itsvinayak** [comment]
@geekcomputers request to close this issue
